### ISSUE TITLE
The installer will clear all system paths if "Add to system path"

### ISSUE THREAD

**Issue by SineStriker** [cnlohr/tinycc-win64-installer#2]
I think it's a fatal bug, because of the dreadful installation lots of command doesn't work.

**Comment by cnlohr** [comment]
I will check this tonight!!! I tested all 3 modes initially.  But thank you for pointing this out!!

**Comment by cnlohr** [comment]
Just confirming, you mean this option, @SineStriker 
![image](https://user-images.githubusercontent.com/2748168/213297553-dab58001-b2f2-422e-b250-202d9e31cd44.png)

If so just tested on Win10.  It worked fine.

What OS version are you using?

**Comment by SineStriker** [comment]
> Just confirming, you mean this option, @SineStriker ![image](https://user-images.githubusercontent.com/2748168/213297553-dab58001-b2f2-422e-b250-202d9e31cd44.png)
> 
> If so just tested on Win10. It worked fine.
> 
> What OS version are you using?

Win10 as well

**Comment by SineStriker** [comment]
The problem doesn't occur now which I don't know why...

**Comment by cnlohr** [comment]
:( I wish I could repro, I've tried several other combinations, but it has never done anything wrong in any of my tests.
